
[general]
	#When the next EMC mapping occurs write the results to config/ProjectE/pregenerated_emc.json and only ever run the mapping again when that file does not exist, this setting is set to false, or an error occurred parsing that file.
	pregenerate = false
	#Want to take a look at the internals of EMC Calculation? Enable this to write all the conversions and setValue-Commands to config/ProjectE/mappingdump.json
	dumpEverythingToFile = false
	#Log known EMC Exploits. This can not and will not find all possible exploits. This will only find exploits that result in fixed/custom emc values that the algorithm did not overwrite. Exploits that derive from conversions that are unknown to ProjectE will not be found.
	logEMCExploits = true

[CraftingMapper]

	[CraftingMapper.MekRotary]
		#Maps Mekanism rotary condensentrator recipes.
		enabled = true

	[CraftingMapper.MekElectrolysis]
		#Maps Mekanism electrolytic separator recipes.
		enabled = true

	[CraftingMapper.MekItemStackGasToItemStack]
		#Maps Mekanism Machine recipes that go from item, gas to item. (Compressing, Purifying, Injecting)
		enabled = true

	[CraftingMapper.MekGasToGas]
		#Maps Mekanism activating recipes.
		enabled = true

	[CraftingMapper.MekItemStackToItemStack]
		#Maps Mekanism Machine recipes that go from item to item. (Crushing, Enriching, Smelting)
		enabled = true

	[CraftingMapper.MekItemStackGasToGas]
		#Maps Mekanism dissolution recipes.
		enabled = true

	[CraftingMapper.MekChemicalInfuser]
		#Maps Mekanism chemical infuser recipes.
		enabled = true

	[CraftingMapper.MekSawmill]
		#Maps Mekanism sawmill recipes. (Disabled by default, due to causing various EMC values to be removed pertaining to charcoal/wood)
		enabled = false

	[CraftingMapper.MekGasToItemStack]
		#Maps Mekanism crystallizing recipes.
		enabled = true

	[CraftingMapper.MekCombiner]
		#Maps Mekanism combiner recipes.
		enabled = true

	[CraftingMapper.MekPressurizedReaction]
		#Maps Mekanism pressurized reaction recipes.
		enabled = true

	[CraftingMapper.MekFluidToFluid]
		#Maps Mekanism evaporating recipes.
		enabled = true

	[CraftingMapper.MekMetallurgicInfuser]
		#Maps Mekanism metallurgic infuser recipes.
		enabled = true

	[CraftingMapper.MekFluidGasToGas]
		#Maps Mekanism washing recipes.
		enabled = true

	[CraftingMapper.MekItemStackToGas]
		#Maps Mekanism item stack to gas recipes. (Gas conversion, Oxidizing)
		enabled = true

	[CraftingMapper.FallbackRecipeType]
		#Fallback for default handling of recipes that extend ICraftingRecipe, AbstractCookingRecipe and SingleItemRecipe. This will catch modded extensions of the vanilla recipe classes, and if the VanillaRecipeTypes mapper is disabled, this mapper will still catch the vanilla recipes.
		enabled = true

	[CraftingMapper.VanillaRecipeTypes]
		#Maps the different vanilla recipe types.
		enabled = true

	[CraftingMapper.MekItemStackToInfuseType]
		#Maps Mekanism item stack to infuse type conversion recipes.
		enabled = true

[enabledMappers]
	#Add Conversions for Crafting Recipes gathered from net.minecraft.item.crafting.RecipeManager
	CraftingMapper = true
	#Adds back and forth conversions of objects and their Tag variant. (EMC values assigned to tags will not behave properly if this mapper is disabled)
	TagMapper = true
	#Add Conversions for Brewing Recipes
	BrewingMapper = true
	#Allows setting EMC values through CraftTweaker. This behaves similarly to if someone used the custom emc file instead.
	CrTCustomEMCMapper = true
	#Add Conversions for the recipes that recolor shulker boxes.
	ShulkerBoxColoringMapper = true
	#Loads json files within datapacks (data/<domain>/pe_custom_conversions/*.json) to add values and conversions
	CustomConversionMapper = true
	#Allows adding custom conversions through CraftTweaker. This behaves similarly to if someone used a custom conversion file instead.
	CrTConversionEMCMapper = true
	#Adds Conversions for fluid container items and fluids.
	FluidMapper = true
	#Set EMC=0 for everything in the forge:ores tag
	OresBlacklistMapper = true
	#Add Conversions for all lingering potions to arrow recipes
	TippedArrowMapper = true
	#Uses the `custom_emc.json` File to add EMC values.
	CustomEMCMapper = true
	#Adds default values for some base resources that are added in Mekanism.
	MekDefaults = true
	#Allows other mods to easily set EMC values using the ProjectEAPI
	APICustomEMCMapper = true

