
#Feature toggles
[cyclic]
	#Disable these items
	sandstoneGear = true
	#Disable these items
	gemObsidianGear = true
	#Disable these items
	emeraldGear = true
	#Disable these items
	netherbrickGear = true
	#Disable this feature
	enchantments = true

