[mysticalcreations]
_comment = ["Check the wiki to learn how to create your seeds! https://github.com/Focamacho/MysticalCreations/wiki"]
seeds = ["cake;3;RESOURCE;INGOT;ROCK;45230E;null", "example;5;MOB;FACE;FLAME;FF0324;minecraft:diamond_block"]
