
#Miscellaneous
[general]
	#The maximum number of twigs that can be found in each chunk
	#Range: 0 ~ 256
	maxTwigsPerChunk = 3
	#The NEW (as of version 1.2.2) way to add bone drops to an entity.
	#Find this name by typing '/summon' in game, and hit TAB.
	boneDropEntities = ["midnight:nightstag", "atum:pharaoh", "atum:sunspeaker", "atum:desert_wolf_alpha", "atum:sergeant", "atum:nomad", "atum:desert_wolf", "atum:camel", "atum:barbarian", "atum:brigand", "atum:warlord", "atum:assassin", "nethercraft:dark_zombie", "nethercraft:bloody_zombie", "nethercraft:tribal_trainee", "nethercraft:tribal_warrior", "nethercraft:tribal_archer", "mysticalworld:silver_fox", "mysticalworld:deer", "minecraft:zombie_villager", "minecraft:zombie_horse", "minecraft:zombie", "minecraft:witch", "minecraft:wandering_trader", "minecraft:vindicator", "minecraft:villager", "minecraft:trader_llama", "minecraft:ravager", "minecraft:pillager", "minecraft:evoker", "minecraft:drowned", "minecraft:donkey", "minecraft:cat", "minecraft:cow", "minecraft:donkey", "minecraft:fox", "minecraft:horse", "minecraft:llama", "minecraft:mooshroom", "minecraft:mule", "minecraft:ocelot", "minecraft:panda", "minecraft:pig", "minecraft:polar_bear", "minecraft:sheep", "minecraft:trader_llama", "minecraft:wolf"]
	#Setting this to true will let players know that they can't break certain blocks without a certain tool
	showToolHelp = true
	#The chance (out of 100) that a bone can drop from the entities in 'boneDropMobs'.
	#Setting this to 0 disables this feature
	#Range: 0 ~ 100
	boneDropFromMobsChance = 50
	#The chance (out of 100) for flint to be created via knapping.
	#e.g.: Setting to 75 means there is a 75% chance knapping will provide flint.
	#Range: 1 ~ 100
	flintKnappingChance = 50
	#Setting this to true prevents the ability to craft stone tools. This is totally unrealistic anyways.
	removeStoneToolRecipes = true
	#Setting this to true will allow you to replace pebbles like tall grass (more convenient for building, but loses the block forever
	arePebblesReplaceable = true
	#A string of dimensions in which pebbles should spawn. See the defaults for the format.
	dimensionWhitelist = ["minecraft:overworld"]
	#The maximum number of pebbles that can be found in each chunk
	#Range: 0 ~ 256
	maxPebblesPerChunk = 5
	#The chance (out of 100) for bone to be created via knapping.
	#e.g.: Setting to 75 means there is a 75% chance knapping will provide a bone shard.
	#Range: 1 ~ 100
	boneShardKnappingChance = 75
	#Setting this to true will make ground blocks (e.g. sand, dirt, gravel) harder to break without the correct tool.
	makeGroundBlocksHarder = true
	#Setting this to true makes it so that plank recipes (including most mods) will not work without a saw or axe.
	removePlankRecipes = true
	#Setting this to true prevents the ability to craft wooden tools. This is totally unrealistic anyways.
	removeWoodenToolRecipes = true

