
#General settings
[general]
	#Multiplier for Obscure tier.
	#Range: 1 ~ 16
	obscure = 1
	#Agitator range base (Modified by tier multiplier)
	#Range: 1 ~ 128
	agitator_range = 4
	#Multiplier for Empowered tier.
	#Range: 1 ~ 16
	empowered = 3
	#Multiplier for Extreme tier.
	#Range: 1 ~ 16
	extreme = 4
	#Multiplier for Base tier.
	#Range: 1 ~ 16
	base = 2

