
["World Gen"]

	["World Gen".Silver]
		"Clusters per Chunk" = 8
		"Blocks per Cluster" = 8
		"Generation Enabled" = false
		"Minimum Y for spawn" = 0
		"Maximum Y for spawn" = 36

	["World Gen".Magmite]
		"Clusters per Chunk" = 6
		"Blocks per Cluster" = 6
		"Generation Enabled" = true
		"Minimum Y for spawn" = 0
		"Maximum Y for spawn" = 21

	["World Gen".Aluminum]
		"Clusters per Chunk" = 10
		"Blocks per Cluster" = 10
		"Generation Enabled" = true
		"Minimum Y for spawn" = 6
		"Maximum Y for spawn" = 48

	["World Gen".Tin]
		"Clusters per Chunk" = 12
		"Blocks per Cluster" = 12
		"Generation Enabled" = false
		"Minimum Y for spawn" = 16
		"Maximum Y for spawn" = 72

	["World Gen".Lead]
		"Clusters per Chunk" = 8
		"Blocks per Cluster" = 8
		"Generation Enabled" = false
		"Minimum Y for spawn" = 0
		"Maximum Y for spawn" = 36

	["World Gen".Copper]
		"Clusters per Chunk" = 12
		"Blocks per Cluster" = 12
		"Generation Enabled" = false
		"Minimum Y for spawn" = 20
		"Maximum Y for spawn" = 80

[Visual]

	[Visual."Machine IO"]

		[Visual."Machine IO"."output1 color"]
			"RGB (0-255)" = "255:128:0"

		[Visual."Machine IO"."input2 color"]
			"RGB (0-255)" = "60:220:60"

		[Visual."Machine IO"."output3 color"]
			"RGB (0-255)" = "240:240:100"

		[Visual."Machine IO"."none color"]
			"RGB (0-255)" = "160:160:160"

		[Visual."Machine IO"."all_output color"]
			"RGB (0-255)" = "240:100:240"

		[Visual."Machine IO"."all_input color"]
			"RGB (0-255)" = "80:220:220"

		[Visual."Machine IO"."input3 color"]
			"RGB (0-255)" = "220:40:40"

		[Visual."Machine IO"."input1 color"]
			"RGB (0-255)" = "80:80:240"

		[Visual."Machine IO"."output2 color"]
			"RGB (0-255)" = "150:0:150"

	[Visual.Machines]
		"Classic GUI's" = false

[Balance]

	[Balance."Generator FE/t"]
		Solid-Fuel = 75
		Refined-Petrol = 240
		LPG = 75
		Oil = 75
		Lava = 75
		Petrol = 150
		Catalyst = 75

