
["Entity AI Settings"]
	#Sets the tick, ticks happen 20 times each sec, interval in which non-running AI tasks are rechecked. Vanilla default is 1, this mods suggested default is 4
	#Range: 1 ~ 500
	goalselectorrate = 4
	#Whether to use a slower updated AI Fox find shelter goal, which causes too much load. default = true
	slowFindShelter = true
	#Whether to use a modified/fixed HurtByTarget goal which is used to call other entities for help. default = true
	optimizeHurtByTarget = true
	#Whether to use a slower updated AI Panic entity goal, panic is used for chickens/other animals running away e.g. on fire. default = true
	optimizePanic = true
	#Whether to use a slower updated AI Breed entity goal, breed is used for searching nearby similar animals and doesnt have to be checked that often. default = true
	optimizeBreed = true
	#Whether to use a more performant Random walking goal, which makes mobs path randomly and can lead to lag default = true
	betterRandomWalking = true
	#Whether to use a slower updated AI tempt goal, tempt is used e.g. for luring sheep with wheat. default = true
	optimizeTempt = true
	#Whether to use a slower updated AI avoid entity goal, avoid is used e.g. for villagers avoiding zombies so it constantly searches for mobs in the area. default = true
	optimizeAvoid = true

["Entity AI Load balancing settings"]
	#TPS(ticks per second) to balance entity AI lag around, this is not a hard cap just a guideline. default = 20
	#Range: 1 ~ 20
	tpsGoal = 20
	#Use load balancing for entity AI. default = true
	AILoadBalancing = true
	#Whether to debug lagging entities and log offenders, requires load balancing to be enabled. default = true
	logEntityAILag = true

[Entities]
	#Use no lag zombies, default = true
	noLagZombies = true

["Tile entities"]
	#Experimental: use slower tile entity update balancing. Enable only when TE lag, e.g. from a tech mod is an issue, affects all TE's! e.g. Furnaces too default = false
	slowTE = false
	#Requires slowTE to be enabled: TPS(ticks per second) to balance entity AI lag around, this is not a hard cap just a guideline. default = 20
	#Range: 1 ~ 20
	teTps = 20
	#Requires slowTE to be enabled: How often TE's should tick at least, default is at least once every 5 ticks. Vanilla is every 1 ticks. default = 5
	#Range: 1 ~ 20
	teTicks = 5

