console.info('Hello, World! (You will only see this line once in console, during startup)')

events.listen('item.registry', function (event) {
    //event.create('').add()

    //Mine
    event.create('flint_gear').add()

    //Tech Reborn
    event.create('empty_cell').add()
    event.create('advanced_alloy_plate').add()
    event.create('aluminum_plate').add()
    event.create('brass_plate').add()
    event.create('bronze_plate').add()
    event.create('carbon_plate').add()
    event.create('chrome_plate').add()
    event.create('coal_plate').add()
    event.create('copper_plate').add()
    event.create('diamond_plate').add()
    event.create('electrum_plate').add()
    event.create('emerald_plate').add()
    event.create('gold_plate').add()
    event.create('invar_plate').add()
    event.create('iridium_alloy_plate').add()
    event.create('iridium_plate').add()
    event.create('iron_plate').add()
    event.create('lapis_plate').add()
    event.create('lazurite_plate').add()
    event.create('lead_plate').add()
    event.create('magnalium_plate').add()
    event.create('nickel_plate').add()
    event.create('obsidian_plate').add()
    event.create('peridot_plate').add()
    event.create('platinum_plate').add()
    event.create('quartz_plate').add()
    event.create('red_garnet_plate').add()
    event.create('redstone_plate').add()
    event.create('refined_iron_plate').add()
    event.create('ruby_plate').add()
    event.create('sapphire_plate').add()
    event.create('silicon_plate').add()
    event.create('silver_plate').add()
    event.create('steel_plate').add()
    event.create('tin_plate').add()
    event.create('titanium_plate').add()
    event.create('tungsten_plate').add()
    event.create('tungstensteel_plate').add()
    event.create('wood_plate').add()
    event.create('yellow_garnet_plate').add()
    event.create('zinc_plate').add()
    event.create('tungstensteel_ingot').add()
    event.create('brass_ingot').add()
    event.create('hot_tungstensteel_ingot').add()
    event.create('iridium_alloy_ingot').add()
    event.create('iridium_ingot').add()
    event.create('mixed_metal_ingot').add()
    event.create('chrome_ingot').add()
    event.create('tungsten_ingot').add()
    event.create('advanced_alloy_ingot').add()
    event.create('titanium_ingot').add()
    event.create('brass_nugget').add()
    event.create('chrome_nugget').add()
    event.create('titanium_nugget').add()
    event.create('tungstensteel_nugget').add()
    event.create('hot_tungstensteel_nugget').add()
    event.create('emerald_nugget').add()
    event.create('iridium_nugget').add()
    event.create('tungsten_nugget').add()
    event.create('peridot_gem').add()
    event.create('red_garnet_gem').add()
    event.create('ruby_gem').add()
    event.create('sapphire_gem').add()
    event.create('yellow_garnet_gem').add()

    //DD&SS
    event.create('sandy_glass_dust').add()
    event.create('white_magic_dust').add()
    event.create('dark_magic_dust').add()

    //Legend of Herobrine
    event.create('cursed_dust').add()
    event.create('cursed_diamond').add()
    event.create('holy_water').add()
    event.create('unholy_water').add()

    //Primal Tech (no official Permission yet)
    //event.create('flint_sawblade').add()

    //Omnifactory
    event.create('primal_earth').add()
    event.create('primal_fire').add()
    event.create('primal_nature').add()
    event.create('primal_water').add()
    event.create('primal_air').add()
    event.create('primal_life').add()
    event.create('mote_of_earth').add()
    event.create('mote_of_fire').add()
    event.create('mote_of_nature').add()
    event.create('mote_of_air').add()
    event.create('mote_of_life').add()
    event.create('endstone_dust').add()
    event.create('carbonado_plate').add()
    event.create('grains_of_innocence').add()
    event.create('micro_circuit').add()
    event.create('micro_processor_array').add()
    event.create('refined_circuit').add()
    event.create('refined_processor').add()
    event.create('refined_processor_array').add()
    event.create('crystal_circuit').add()
    event.create('crystal_processor_array').add()
    event.create('combination_circuit').add()
    event.create('nano_processor_array').add()
    event.create('quantum_processor').add()
    event.create('quantum_processor_array').add()
    event.create('electronic_processor').add()
    event.create('electronic_processor_array').add()
    event.create('micro_processor_mainframe').add()
    event.create('nano_processor_mainframe').add()
    event.create('refined_processor_mainframe').add()
    event.create('quantum_processor_mainframe').add()

    //FTB Interactions (no official Permission yet)
    //event.create('enriched_egg').add()
    //event.create('infinity_egg').add()

    //Project Ozone 3 (textures not working)
    //event.create('chaos_ingot').add()
    //event.create('chaos_catalyst').add()

    //All the Mods 3 - Remix (No official Permission yet)
    //event.create('bloody_mana_infused_time_dust').add()
    //event.create('mana_infused_time_dust').add()
    //event.create('roasted_time_dust').add()
    //event.create('sands_of_time_acceleration').add()
})